email: q.odding+6wz7wymt@outlook.com
custom_css: assets/css/custom.css
github_url: ""
repository_url: ""
title: Houthof
description: De natuurlijke versie van het Knarrenhof
plugins:
  - jekyll-seo-tag
sass:
  style: compressed
